import { createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';

/**
 * A shared passcode is a gate, not an identity. It keeps passers-by out; it
 * cannot tell us who walked in, and it cannot be taken away from one person
 * without taking it from everyone — which is why the list below carries a label
 * and an expiry per entry, so one leak costs one entry.
 */

export interface PasscodeEntry {
  label: string;
  hash: string;
  salt: string;
  /** ISO date; past this the entry stops working without a redeploy of others */
  expires?: string;
}

const SCRYPT = { N: 16384, r: 8, p: 1, maxmem: 64 * 1024 * 1024 };

export function hashPasscode(passcode: string, saltHex: string): string {
  return scryptSync(passcode.normalize('NFKC'), Buffer.from(saltHex, 'hex'), 32, SCRYPT).toString('hex');
}

export function newSalt(): string {
  return randomBytes(16).toString('hex');
}

/**
 * `UPCGM_PASSCODES` holds `label:salt:hash` triples separated by commas, with an
 * optional `:YYYY-MM-DD` expiry. Generated by `npm run passcode`.
 */
function loadEntries(): PasscodeEntry[] {
  const raw = process.env.UPCGM_PASSCODES;
  if (!raw) return [];
  return raw
    .split(',')
    .map((chunk) => chunk.trim())
    .filter(Boolean)
    .map((chunk) => {
      const [label, salt, hash, expires] = chunk.split(':');
      return { label, salt, hash, expires };
    })
    .filter((e) => e.label && e.salt && e.hash);
}

export interface VerifyResult {
  ok: boolean;
  label?: string;
  reason?: 'no-config' | 'expired' | 'mismatch';
}

export function verifyPasscode(input: string): VerifyResult {
  const entries = loadEntries();
  if (entries.length === 0) return { ok: false, reason: 'no-config' };

  const candidate = input.trim();
  let expiredMatch = false;

  for (const entry of entries) {
    const expected = Buffer.from(entry.hash, 'hex');
    // Hash first so both sides are 32 bytes: comparing raw input would leak the
    // passcode length through timingSafeEqual's length check.
    const actual = Buffer.from(hashPasscode(candidate, entry.salt), 'hex');
    if (actual.length !== expected.length) continue;
    if (!timingSafeEqual(actual, expected)) continue;

    if (entry.expires && new Date(entry.expires).getTime() < Date.now()) {
      expiredMatch = true;
      continue;
    }
    return { ok: true, label: entry.label };
  }
  return { ok: false, reason: expiredMatch ? 'expired' : 'mismatch' };
}

export interface SessionPayload {
  v: 1;
  label: string;
  iat: number;
  exp: number;
}

const b64u = (b: Buffer) => b.toString('base64url');

function secret(): string {
  const s = process.env.UPCGM_SESSION_SECRET;
  if (!s || s.length < 32) {
    throw new Error('UPCGM_SESSION_SECRET is missing or too short (need ≥32 chars)');
  }
  return s;
}

export const SESSION_COOKIE = 'upcgm_s';
export const SESSION_TTL_SECONDS = 12 * 60 * 60;

export function signSession(label: string): string {
  const now = Math.floor(Date.now() / 1000);
  const payload: SessionPayload = { v: 1, label, iat: now, exp: now + SESSION_TTL_SECONDS };
  const body = b64u(Buffer.from(JSON.stringify(payload)));
  const mac = b64u(createHmac('sha256', secret()).update(body).digest());
  return `${body}.${mac}`;
}

export function verifySession(token: string | undefined | null): SessionPayload | null {
  if (!token) return null;
  const [body, mac] = token.split('.');
  if (!body || !mac) return null;
  const expected = createHmac('sha256', secret()).update(body).digest();
  let given: Buffer;
  try { given = Buffer.from(mac, 'base64url'); } catch { return null; }
  if (given.length !== expected.length || !timingSafeEqual(given, expected)) return null;
  try {
    const payload = JSON.parse(Buffer.from(body, 'base64url').toString()) as SessionPayload;
    if (payload.v !== 1) return null;
    if (payload.exp < Math.floor(Date.now() / 1000)) return null;
    return payload;
  } catch {
    return null;
  }
}
